# Become Ubuntu 14.04 Trusty 
dist: trusty

language: cpp

addons:
    apt:
        packages:
            - cmake
            - libboost-all-dev
            - cppcheck
            - clang-3.6
            - clang-format-3.6
            - valgrind
            - doxygen
            - curl

compiler:
  - gcc

os:
  - linux

before_install:
  - "curl -s https://packagecloud.io/install/repositories/uilianries/poco/script.deb.sh | sudo bash && sudo apt-get install libpoco-1.7=1.7-1"

script:
  - script/linter.sh
  - script/static-analysis.sh
  - script/build.sh
  - script/valgrind.sh build/test/test_gpio

branches:
  only:
    - develop
