# Become Ubuntu 14.04 Trusty 
sudo: required
dist: trusty

language: 
  - cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake libboost-all-dev

script:
  - mkdir build
  - cd build
  - cmake .. && make && test/test_gpio

branches:
  only:
    - develop
