# Become Ubuntu 14.04 Trusty 
sudo: required
dist: trusty

language: 
  - cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake libgtest-dev libboost-all-dev
  - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"

script:
  - mkdir build
  - cd build
  - cmake .. && make && test/test_gpio

branches:
  only:
    - develop
