# Become Ubuntu 14.04 Trusty 
sudo: required
dist: trusty

language: cpp

compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5


os:
  - linux

before_install:
  - sudo apt-get install -y -qq cmake libboost1.55-all-dev cppcheck clang-3.6 clang-format-3.6 valgrind doxygen curl
  - wget https://github.com/uilianries/3rdParty/blob/master/libpoco_1.7-amd64.deb && sudo dpkg -i libpoco_1.7-amd64.deb

install:
  if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

script:
  - script/doxygen.sh
  - script/linter.sh
  - script/static-analysis.sh
  - script/build.sh --install
  - script/valgrind.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - develop
    - master
