# Become Ubuntu 14.04 Trusty 
sudo: required
dist: trusty

language: 
  - cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake libboost-all-dev
  - sudo apt-get install clang-3.6
  - sudo apt-get install cppcheck

script:
  - script/linter.sh
  - script/static-analysis.sh
  - mkdir build
  - cd build
  - cmake .. && make && test/test_gpio

branches:
  only:
    - develop
