# Become Ubuntu 14.04 Trusty 
dist: trusty

language: cpp

addons:
    apt:
        packages:
            - cmake
            - libboost-all-dev
            - cppcheck
            - clang-3.6
            - clang-format-3.6
            - valgrind
            - doxygen

compiler:
  - gcc

os:
  - linux

before_install:
  - "wget https://packagecloud.io/uilianries/poco/packages/ubuntu/trusty/libpoco-1.7_1.7-1_amd64.deb && sudo dpkg -i libpoco-1.7_1.7-1_amd64.deb"

script:
  - script/linter.sh
  - script/static-analysis.sh
  - script/build.sh
  - script/valgrind.sh build/test/test_gpio

branches:
  only:
    - develop
